# Generated by Django 5.2.3 on 2025-07-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.attendancerecord')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='clock_in',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='clock_out',
        ),
    ]
